### ISSUE TITLE
Consumer uses 100% CPU

### ISSUE THREAD

**Issue by Miggets7** [jmf-mordis/asynckafka#6]
When polling for messages like this:

```
self.consumer.start()

async for message in self.consumer:
```

The CPU immediately goes to 100%

Having several consumers will use all CPU cores available and freeze the system. Is there a way to lower the CPU usage?

**Comment by jmf-mordis** [comment]
Thanks for reporting the error.

Could you provide an example where the error is reproduced? Does it occur when the consumer is in IDLE waiting for messages? or when it is behind in the offset consuming messages?

**Comment by Miggets7** [comment]
Yes, it occurs when waiting for messages.

I've got a consumer waiting on a topic which starts and stops consumers depending on the data coming in the topic:

```
await self.consumer.start()

async for message in self.consumer:
    try:
        sink_config = KafkaMongoConfig.from_json(message.value)
        if sink_config.active:
            await self.start_sink_deployment(sink_config)
        else:
            await self.stop_sink_deployment(sink_config.id)
    except Exception as e:
        print(e)
        await self.consumer.stop()
```

This is how `start_sink_deployment` looks:
```
async def start_sink_deployment(self, sink_config: KafkaMongoConfig):
        old_deployment = self.deployments.get(sink_config.id)
        if old_deployment is not None:
            await old_deployment.stop()
            self.deployments.pop(sink_config.id)

        deployment = KafkaMongoSink(sink_config, sink_config.reset_offset)
        await deployment.start()

        self.deployments[sink_config.id] = deployment
```
And this is the code in the `KafkaMongoSink` class:

```
 def __init__(self, sink_config: KafkaMongoConfig, reset_offset):
        self.loop = asyncio.get_event_loop()
        self.consumer = AIOKafkaConsumer(
                    self.sink_config.topic_target,
                    loop=self.loop,
                    bootstrap_servers=KAFKA_HOST,
                    auto_offset_reset="latest",
                    key_deserializer=lambda x: x.decode("utf-8"),
                    value_deserializer=lambda x: json.loads(x.decode("utf-8")))

async def start(self):
        await self.consumer.start()
        self.task = asyncio.create_task(self.process_data())

    async def process_data(self):
        operations = []
        async for message in self.consumer:
            try:
                delayed_task.cancel()
                msg_json = message.value
               ...
```

When the main consumer is in the loop, I see the CPU using 100%
With each consumer stating, another 100% CPU is used.

It looks like a `while true` kind of thing.

**Comment by Miggets7** [comment]
Any progress on this issue?

**Comment by jmf-mordis** [comment]
Hey Miggets7, there is a `while true` in the code because the consumer needs to do some polling internally to rdkafka. But it only does it periodically because it does a asyncio sleep.

I suspect that the 100% of CPU usage is because the `async for` it is not running in a coroutine and the asyncio sleep (and asyncio in general) is not correctly working.

Look to this example: https://github.com/jmf-mordis/asynckafka/blob/master/examples/consumer.py

Is your `async for` inside a coroutine like in the example?

Sonrry for the delay in the reply.

**Comment by Miggets7** [comment]
Hi jmf-mordis,

Sorry for the late reply, but you were right, I was using it wrongly with asyncio. I managed to do it correctly now.

Thank you for your time and help.

PS: ¡Muchos gracias por partir esta biblioteca tan fantástico!
